import {
  ArrowDown,
  ArrowUp,
  ArrowLeft,
  ArrowRight,
  LayoutDashboard,
  Mail,
  Phone,
  Plus,
  Settings,
  UserRound,
  Search,
  ChevronRight,
  Bell,
  Clock,
  TvMinimal,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  Crop,
  Maximize,
  Upload,
  X,
  Filter,
} from 'lucide-react';
import {
  RiCheckboxCircleFill,
  RiCheckLine,
  RiEarthLine,
  RiErrorWarningLine,
  RiEye2Line,
  RiEyeOffLine,
  RiBox2Line,
  RiBardLine,
  RiSendPlaneLine,
  RiFlashlightLine,
  RiBillLine,
  RiDashboardHorizontalLine,
  RiQuestionLine,
  RiMailSendLine,
  RiTicket2Line,
  RiGoogleLine,
} from '@remixicon/react';

// register your icons here as your requirements
export const Icons = {
  arrow_up: ArrowUp,
  arrow_down: ArrowDown,
  eye: RiEye2Line,
  eye_off: RiEyeOffLine,
  setting: Settings,
  earth: RiEarthLine,
  check: RiCheckLine,
  dashboard: LayoutDashboard,
  ticket: RiTicket2Line,
  client: UserRound,
  mail: Mail,
  send: RiSendPlaneLine,
  phone: Phone,
  plus: Plus,
  spam: RiBox2Line,
  aiassistant: RiBardLine,
  trigger: RiFlashlightLine,
  support: RiBillLine,
  plugins: RiDashboardHorizontalLine,
  help: RiQuestionLine,
  ticketResolved: RiMailSendLine,
  search: Search,
  chevron_right: ChevronRight,
  notification: Bell,
  clock: Clock,
  screen: TvMinimal,
  chevron_down: ChevronDown,
  chevron_up: ChevronUp,
  arrow_left: ArrowLeft,
  arrow_right: ArrowRight,
  chevron_left: ChevronLeft,
  google: RiGoogleLine,
  chevronLeft: ChevronLeft,
  error_warning: RiErrorWarningLine,
  checbox_circle: RiCheckboxCircleFill,
  x: X,
  crop: Crop,
  maximize: Maximize,
  upload: Upload,
  filter: Filter,
};
