import {
  ArrowDown,
  ArrowUp,
  ArrowLeft,
  ArrowRight,
  LayoutDashboard,
  Mail,
  Phone,
  Plus,
  Settings,
  UserRound,
  Search,
  ChevronRight,
  Bell,
  Clock,
  TvMinimal,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  Crop,
  Maximize,
  Upload,
  X,
  Copy,
  MoreVertical,
  Check,
  Tag,
  PlusCircle,
  MessageCircle,
  UserCheck,
  Book,
  CircleAlert,
  ExternalLink,
  UserPlus,
  Filter,
  Info,
  Reply,
  ArrowUpCircle,
} from 'lucide-react';
import {
  RiCheckboxCircleFill,
  RiCheckLine,
  RiEarthLine,
  RiErrorWarningLine,
  RiEye2Line,
  RiEyeOffLine,
  RiBox2Line,
  RiBardLine,
  RiSendPlaneLine,
  RiFlashlightLine,
  RiBillLine,
  RiDashboardHorizontalLine,
  RiQuestionLine,
  RiMailSendLine,
  RiTicket2Line,
  RiGoogleLine,
  RiWhatsappFill,
  RiCheckDoubleLine,
  RiContactsBook2Fill,
  RiContactsBook2Line,
  RiComputerLine,
  RiInstagramFill,
  RiFacebookFill,
  RiTwitterFill,
  RiLinkedinBoxFill,
  RiRocketLine,
  RiSearchEyeLine,
  RiPencilFill,
  RiEdit2Fill,
  RiEyeFill,
  RiDeleteBin5Line,
  RiUserSettingsFill,
  RiUserFill,
  RiCalendarLine,
  RiChatAiFill,
  RiIndeterminateCircleFill,
  RiMapPinLine,
  RiAppleLine,
  RiWindowLine,
  RiLoginBoxLine,
  RiDeleteBin7Fill,
  RiStarFill,
  RiUserLine,
  RiContactsBookLine,
  RiCloseCircleFill,
  RiTimeFill,
} from '@remixicon/react';

// register your icons here as your requirements
export const Icons = {
  arrow_up: ArrowUp,
  arrow_down: ArrowDown,
  eye: RiEye2Line,
  eye_off: RiEyeOffLine,
  setting: Settings,
  earth: RiEarthLine,
  check: RiCheckLine,
  dashboard: LayoutDashboard,
  ticket: RiTicket2Line,
  client: UserRound,
  mail: Mail,
  send: RiSendPlaneLine,
  phone: Phone,
  plus: Plus,
  spam: RiBox2Line,
  aiassistant: RiBardLine,
  trigger: RiFlashlightLine,
  support: RiBillLine,
  plugins: RiDashboardHorizontalLine,
  help: RiQuestionLine,
  ticketResolved: RiMailSendLine,
  search: Search,
  chevron_right: ChevronRight,
  notification: Bell,
  clock: Clock,
  screen: TvMinimal,
  chevron_down: ChevronDown,
  chevron_up: ChevronUp,
  arrow_left: ArrowLeft,
  arrow_right: ArrowRight,
  chevron_left: ChevronLeft,
  google: RiGoogleLine,
  chevronLeft: ChevronLeft,
  error_warning: RiErrorWarningLine,
  checbox_circle: RiCheckboxCircleFill,
  x: X,
  crop: Crop,
  maximize: Maximize,
  upload: Upload,
  success_toast: Check,
  danger: CircleAlert,
  rocket: RiRocketLine,
  search_eye: RiSearchEyeLine,
  pencil: RiPencilFill,
  copy: Copy,
  external_link: ExternalLink,
  user_plus: UserPlus,
  filter: Filter,
  whatsapp: RiWhatsappFill,
  double_check: RiCheckDoubleLine,
  more_vertical: MoreVertical,
  contact_line: RiContactsBook2Line,
  computer: RiComputerLine,
  tag: Tag,
  plus_circle: PlusCircle,
  message: MessageCircle,
  user_check: UserCheck,
  book: Book,
  instagram: RiInstagramFill,
  facebook: RiFacebookFill,
  twitter: RiTwitterFill,
  linkedin: RiLinkedinBoxFill,
  info: Info,
  ri_edit2_fill: RiEdit2Fill,
  ri_eye_fill: RiEyeFill,
  ri_delete_bin_5_line: RiDeleteBin5Line,
  ri_user_settings_fill: RiUserSettingsFill,
  ri_user_fill: RiUserFill,
  ri_user_line: RiUserLine,
  reply: Reply,
  ri_delete_bin_7_fill: RiDeleteBin7Fill,
  ri_star_fill: RiStarFill,
  ri_contacts_book_line: RiContactsBookLine,
  ri_close_circle_fill: RiCloseCircleFill,
  arrow_up_circle: ArrowUpCircle,
  ri_chat_ai_fill: RiChatAiFill,
  ri_indeterminate_circle_fill: RiIndeterminateCircleFill,
  ri_map_pin_line: RiMapPinLine,
  ri_apple_line: RiAppleLine,
  ri_window_line: RiWindowLine,
  ri_login_box_line: RiLoginBoxLine,
  ri_calendar_line: RiCalendarLine,
  ri_time_fill: RiTimeFill, //added arrow down by rahul
};
